import requests
import time
import pickle

subject_categories = sorted(set([
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Statistics",
    "Astronomy",
    "Geology",
    "Environmental Science",
    "Computer Science",
    "Medicine",
    "Genetics",
    "Biophysics",
    "Biomechanics",
    "Ecology",
    "Biotechnology",
    "Bioinformatics",
    "Neuroscience",
    "Biochemistry",
    "Microbiology",
    "Cell Biology",
    "Molecular Biology",
    "Evolution",
    "Botany",
    "Zoology",
    "Meteorology",
    "Oceanography",
    "Geography",
    "Geophysics",
    "Physical Chemistry",
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Analytical Chemistry",
    "Biochemistry",
    "Biophysical Chemistry",
    "Environmental Chemistry",
    "Materials Science",
    "Quantum Mechanics",
    "Thermodynamics",
    "Statistics",
    "Biophysics",
    "Pharmacology",
    "Anthropology",
    "Psychology",
    "Sociology",
    "Paleontology",
    "Archaeology",
    "Economics",
    "Political Science",
    "History",
    "Agricultural Science",
    "Forensic Science",
    "Political Science",
    "Library Science",
    "Information Science",
    "Cognitive Science",
    "Neuroscience",
    "Linguistics",
    "Semiotics",
    "Philosophy of Science",
    "History of Science",
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Reinforcement Learning",
    "Computer Vision",
    "Natural Language Processing",
    "Speech Processing",
    "Audio Processing",
    "Music Processing",
    "Image Processing",
    "Video Processing",
    "Signal Processing",
    "Time Series Analysis",
    "Financial Analysis",
    "Economic Analysis",
    "Social Network Analysis",
    "Biological Analysis",
    "Human-Computer Interaction",
    "Computer Graphics",
    "Computer Animation",
    "Computer Simulation",
    "Computer Modeling",
    "Computer Visualization",
    "History",
    "Geography",
    "Economics",
    "Business",
    "Law",
    "Education",
    "Philosophy",
    "Religion",
    "Literature",
    "Art",
    "Music",
    "Film",
    "Theater",
    "Dance",
    "Photography",
    "Architecture",
    "Design",
    "Fashion",
    "Culinary Arts",
    "Sports",
    "Games",
    "Travel",
    "Hobbies",
    "Crafts",
    "Gardening",
    "Pets",
    "Health",
    "Fitness",
    "Nutrition",
    "Parenting",
    "Relationships",
    "Self-Help",
    "Motivation",
    "Spirituality",
    "Astrology",
    "Paranormal",
    "True Crime",
    "Humor",
    "Comics",
    "Graphic Novels",
    "Science Fiction",
    "Fantasy",
    "Mystery",
    "Thriller",
    "Horror",
    "Romance",
    "Historical Fiction",
    "Poetry",
    "Drama",
    "Classic Literature",
    "Logic",
    "Theoretical Computer Science",
    "Information Theory",
    "Systems Theory",
    "Decision Theory",
    "Game Theory",
    "Control Theory",
    "Automata Theory",
    "Computational Complexity Theory",
    "Computational Learning Theory",
    "Computational Number Theory",
    "Computational Group Theory",
    "Computational Geometry",
    "Computational Topology",
    "Computational Algebraic Geometry",
    "Computational Commutative Algebra",
    "Computational Representation Theory",
    "Computational Harmonic Analysis",
    "Computational Functional Analysis",
    "Computational Differential Equations",
    "Computational Partial Differential Equations",
    "Computational Integral Equations",
    "Computational Stochastic Processes",
    "Computational Probability Theory",
    "Computational Statistics",
    "Computational Data Analysis",
    "Computational Machine Learning",
    "Computational Deep Learning",
    "Computational Reinforcement Learning",
    "Computational Robotics",
    "Computational Computer Vision",
    "Computational Natural Language Processing",
    "Computational Speech Processing",
    "Computational Audio Processing",
    "Computational Music Processing",
    "Computational Image Processing",
    "Computational Video Processing",
    "Computational Signal Processing",
    "Computational Time Series Analysis",
    "Computational Financial Analysis",
    "Computational Economic Analysis",
    "Computational Social Network Analysis",
    "Computational Biological Analysis",
    "Human-Computer Interaction",
    "Computer Graphics",
    "Computer Vision",
    "Computer Animation",
    "Computer Simulation",
    "Computer Modeling",
    "Computer Visualization",
    "Computer Augmented Reality",
    "Computer Virtual Reality",
    "Computer Mixed Reality",
    "Computer Hyper Reality",
    "Computer Simulated Reality",
    "Computer Artificial Reality",
    "Computer Synthetic Reality",
    "Computer Extended Reality",
    "Computer Immersive Reality",
    "Computer Interactive Reality",
    "Computer Collaborative Reality",
    "Computer Distributed Reality",
    "Computer Networked Reality",
    "Computer Social Reality",
    "Computer Collective Reality",
    "Computer Ambient Reality",
    "Computer Pervasive Reality",
    "Computer Ubiquitous Reality",
    "Chemical Engineering",
    "Biomolecular Engineering",
    "Materials Engineering",
    "Process Engineering",
    "Civil Engineering",
    "Environmental Engineering",
    "Fire Protection Engineering",
    "Sanitary Engineering",
    "Municipal or Urban Engineering",
    "Irrigation Engineering",
    "Electrical Engineering",
    "Electronics Engineering",
    "Telecommunications Engineering",
    "Power Engineering",
    "Mechanical Engineering",
    "Aerospace Engineering",
    "Automotive Engineering",
    "Marine Engineering",
    "Nuclear Engineering",
    "Mining Engineering",
    "Petroleum Engineering",
    "Software Engineering",
    "Systems Engineering",
    "Structural Engineering",
    "Transportation Engineering",
    "Geotechnical Engineering",
    "Hydraulic Engineering",
    "Coastal Engineering",
    "Ocean Engineering",
    "Water Resources Engineering",
    "Energy Engineering",
    "Acoustical Engineering",
    "Manufacturing Engineering",
    "Thermal Engineering",
    "Sports Engineering",
    "Biomedical Engineering",
    "Agricultural Engineering",
    "Aquaculture Engineering",
    "Food Engineering",
    "Bioprocess Engineering",
    "Biotechnology Engineering",
    "Genetic Engineering",
    "Pharmaceutical Engineering",
    "Tissue Engineering",
    "Regenerative Medicine Engineering",
    "Neural Engineering",
    "Rehabilitation Engineering",
    "Clinical Engineering",
    "Health Systems Engineering",
    "Industrial Engineering",
    "Operations Research",
    "Engineering Management",
    "Logistics Engineering",
    "Supply Chain Engineering",

]))

valid_categories = []


# open text file in write mode
fo = open("subject_categories_free_ebook.csv", "w+", encoding='utf-8')
print("Category,num_books", file=fo)


for sub in subject_categories:
    url = "https://www.googleapis.com/books/v1/volumes" #
    params = {
        "q": f'insubject:"{sub}"', 
        "filter": "free-ebooks", 
        "maxResults": 40,
        "orderBy": "relevance",  
        "langRestrict": "en"
    }

    # makes the API request
    raw_response = requests.get(url, params=params)
    # wait for 1 second
    time.sleep(1)

    if raw_response.status_code != 200:
        print(f"Error: {raw_response.status_code}")
        continue

    items = raw_response.json()

    if items['totalItems'] > 0:
        print(f"{sub}:{items['totalItems']} books found")
        print(f"{sub},{items['totalItems']}", file=fo)
    else:
        print(f"{sub}: No books found")


fo.close()